main: com.gaarnik.blacksmithtycoon.BlacksmithTycoonPlugin
name: BlacksmithTycoon
version: 1.0
api-version: 1.15

commands:
  ping:
    description: Simple Ping / Pong command
    usage: /ping
  blacksmithspawn:
    description: Spawn the Blacksmith Master
    usage: /blacksmithspawn