main: com.gaarnik.blacksmithtycoon.BlacksmithTycoonPlugin
name: BlacksmithTycoon
version: "1.0"
api-version: "1.15"

depend: [Vault]

commands:
  blacksmithspawn:
    description: Spawn the Blacksmith Master
    usage: /blacksmithspawn